eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.190:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: huayifeign1
  cloud:



# sqlserver 属性配置
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.1.192;instanceName=sql;DatabaseName=WeiXinKecheng
    username: pqb
    password: pqb
